USE socialmetrics;

-- Jeu de donnees annotees pour SocialMetrics AI.
-- Convention d'annotation :
--   positive = 1 si le tweet exprime un sentiment positif, 0 sinon
--   negative = 1 si le tweet exprime un sentiment negatif, 0 sinon
--   (0, 0) = neutre / factuel        (1, 1) = mixte (positif et negatif)
-- Le jeu contient des exemples anglais et francais afin d'entrainer
-- les deux modeles de regression logistique (positif et negatif).

INSERT INTO tweets (text, positive, negative) VALUES
-- ------------------------------------------------------------------
-- Positifs (positive = 1, negative = 0)
-- ------------------------------------------------------------------
('I love this product, it works perfectly', 1, 0),
('Amazing service and very friendly support', 1, 0),
('This update is excellent and useful', 1, 0),
('The experience was smooth and pleasant', 1, 0),
('Excellent quality and fast delivery', 1, 0),
('I am happy with this reliable service', 1, 0),
('Perfect result, very useful and clean', 1, 0),
('Best purchase I have made this year', 1, 0),
('The new feature is fantastic and easy to use', 1, 0),
('Customer support solved my issue in minutes, great job', 1, 0),
('Super fast shipping and the packaging was beautiful', 1, 0),
('This app makes my daily work so much easier', 1, 0),
('Absolutely delighted with the results', 1, 0),
('The team was professional and very helpful', 1, 0),
('Wonderful design and intuitive interface', 1, 0),
('Highly recommend this to everyone', 1, 0),
('Great value for money, totally worth it', 1, 0),
('The performance improved a lot after the last patch', 1, 0),
('Smooth onboarding, everything just works', 1, 0),
('I appreciate how responsive the developers are', 1, 0),
('Impressive battery life and a gorgeous screen', 1, 0),
('The tutorial was clear and very well made', 1, 0),
('So glad I switched, the difference is night and day', 1, 0),
('Fantastic experience from start to finish', 1, 0),
('The refund was processed quickly and without hassle', 1, 0),
('Bon service et tres bonne qualite', 1, 0),
('Application rapide, fluide et vraiment agreable', 1, 0),
('Je suis ravi de mon achat, je recommande', 1, 0),
('Le support client a ete reactif et efficace', 1, 0),
('Interface claire et tres facile a utiliser', 1, 0),
('Livraison rapide et produit conforme, parfait', 1, 0),
('Une mise a jour excellente qui ameliore tout', 1, 0),
('Genial, tout fonctionne du premier coup', 1, 0),
('Rapport qualite prix imbattable, je suis conquis', 1, 0),
('Merci a l equipe pour ce travail remarquable', 1, 0),
-- Exemples reutilisant un vocabulaire positif recurrent (love, great, best...)
('I love this app so much', 1, 0),
('I love the new design, it is great', 1, 0),
('Great job, this update is great', 1, 0),
('Great support and great quality', 1, 0),
('This is the best app I have ever used', 1, 0),
('Best service ever, I love it', 1, 0),
('Amazing quality, amazing support, I love it', 1, 0),
('Excellent work, truly excellent and reliable', 1, 0),
('Perfect experience, everything is perfect', 1, 0),
('Happy customer, this service is wonderful', 1, 0),
('Wonderful update, I am so happy', 1, 0),
('Fantastic quality and fantastic support', 1, 0),
('J adore cette application, elle est geniale', 1, 0),
('J adore le nouveau design, vraiment super', 1, 0),
('Super service et super qualite, merci', 1, 0),
('Excellent produit, excellente livraison', 1, 0),
('Parfait, tout est parfait et rapide', 1, 0),

-- ------------------------------------------------------------------
-- Negatifs (positive = 0, negative = 1)
-- ------------------------------------------------------------------
('I hate this app, it crashes all the time', 0, 1),
('Terrible support and very bad quality', 0, 1),
('This is disappointing and completely broken', 0, 1),
('The service is slow, expensive and useless', 0, 1),
('Bad experience, I am angry and disappointed', 0, 1),
('Awful product, useless and frustrating', 0, 1),
('Worst update ever, nothing works', 0, 1),
('Customer service ignored my messages for days', 0, 1),
('The app freezes every time I open it', 0, 1),
('Completely unusable after the latest update', 0, 1),
('I want a refund, this is a scam', 0, 1),
('The quality is cheap and it broke in a week', 0, 1),
('Painfully slow and full of bugs', 0, 1),
('Do not buy this, waste of money', 0, 1),
('The interface is confusing and ugly', 0, 1),
('Shipping was late and the box was damaged', 0, 1),
('It stopped working after two days, very poor', 0, 1),
('The support team was rude and unhelpful', 0, 1),
('Constant errors and crashes, unacceptable', 0, 1),
('Overpriced and underwhelming, deeply disappointed', 0, 1),
('The battery drains way too fast, terrible', 0, 1),
('Full of ads and impossible to navigate', 0, 1),
('This is the worst experience I have ever had', 0, 1),
('Broken promises and no real fixes', 0, 1),
('Horrible performance, it lags constantly', 0, 1),
('Mauvaise experience, service lent et horrible', 0, 1),
('Application catastrophique, elle plante sans arret', 0, 1),
('Support client inexistant, je suis furieux', 0, 1),
('Produit de mauvaise qualite, casse en une semaine', 0, 1),
('Trop cher pour un resultat decevant', 0, 1),
('Livraison en retard et colis abime, honteux', 0, 1),
('Interface confuse et pleine de bugs', 0, 1),
('Je regrette cet achat, argent gaspille', 0, 1),
('Mise a jour ratee, plus rien ne fonctionne', 0, 1),
('Le pire service que j ai jamais rencontre', 0, 1),
-- Exemples reutilisant un vocabulaire negatif recurrent (hate, terrible, worst...)
('I hate this update, it is terrible', 0, 1),
('I hate this app, it is so bad', 0, 1),
('Terrible service and terrible quality', 0, 1),
('This is the worst app I have ever used', 0, 1),
('Worst update ever, absolutely terrible', 0, 1),
('Awful support and awful experience', 0, 1),
('Horrible quality, horrible service', 0, 1),
('Bad app, bad support, very bad', 0, 1),
('Useless update, completely useless', 0, 1),
('Disappointing service, very disappointing', 0, 1),
('I am so disappointed, this is awful', 0, 1),
('Broken again, this app is terrible', 0, 1),
('Je deteste cette application, elle est horrible', 0, 1),
('Je deteste ce service, vraiment mauvais', 0, 1),
('Service horrible et qualite horrible', 0, 1),
('Le pire produit, vraiment terrible', 0, 1),
('Application inutile, totalement inutile', 0, 1),

-- ------------------------------------------------------------------
-- Neutres / factuels (positive = 0, negative = 0)
-- ------------------------------------------------------------------
('The interface is acceptable but not special', 0, 0),
('The announcement was neutral and factual', 0, 0),
('The update will be released next Tuesday', 0, 0),
('The app is available on iOS and Android', 0, 0),
('Version 2.1 includes minor changes', 0, 0),
('The meeting is scheduled for 3 pm today', 0, 0),
('The product weighs about two kilograms', 0, 0),
('Support hours are from 9 am to 6 pm', 0, 0),
('The documentation covers the installation steps', 0, 0),
('It comes in three colors: black, white and blue', 0, 0),
('The server will restart during maintenance', 0, 0),
('The report contains data from last quarter', 0, 0),
('You can change the language in the settings', 0, 0),
('The package includes a charger and a cable', 0, 0),
('The webinar starts at noon on Friday', 0, 0),
('La mise a jour sera disponible la semaine prochaine', 0, 0),
('Le produit est disponible en plusieurs tailles', 0, 0),
('La reunion aura lieu demain a quatorze heures', 0, 0),
('Le service client est ouvert du lundi au vendredi', 0, 0),
('La documentation explique les etapes d installation', 0, 0),

-- ------------------------------------------------------------------
-- Mixtes (positive = 1, negative = 1)
-- ------------------------------------------------------------------
('Great design but the performance is poor', 1, 1),
('Useful features, although the setup is painful', 1, 1),
('I love the concept but it is way too buggy', 1, 1),
('Fast delivery but the product was defective', 1, 1),
('Nice interface, however it crashes often', 1, 1),
('The support is friendly but very slow to respond', 1, 1),
('Powerful tool, yet the price is too high', 1, 1),
('Beautiful screen but the battery is disappointing', 1, 1),
('Good idea, poor execution', 1, 1),
('The food was delicious but the service was awful', 1, 1),
('Bon produit mais le service apres vente est decevant', 1, 1),
('J aime le design mais l application est trop lente', 1, 1),
('Fonctionnalites utiles mais l installation est penible', 1, 1),
('Livraison rapide mais article defectueux', 1, 1),
('Excellente idee mais realisation ratee', 1, 1);
